### ISSUE TITLE
Kendall's Tau Error

### ISSUE THREAD

**Issue by maxkuhn** [michellab/freenrgworkflows#13]
The following files give "1.00 < 0.95 < 1.00" as output for Kendall's Tau.

- [thrombin_ds_dGexp.txt](https://github.com/michellab/freenrgworkflows/files/2600681/thrombin_ds_dGexp.txt)

- [fep_results_freenrgworkflow.txt](https://github.com/michellab/freenrgworkflows/files/2600682/fep_results_freenrgworkflow.txt)

Note: I have renamed the files from .csv to .txt since GitHub does not allow me to upload csv files.
 
I have added the following simple lines (which do not allow for target compound selection) to the jupyter notebook to read in the experimental dG values, :

experiments = n_ex.ExperimentalData()
kcal_file = 'thrombin_ds_dGexp.csv'
experiments.read_free_energies(kcal_file)
experimental_DDGs = experiments.freeEnergiesInKcal
pG.write_free_energies(experimental_DDGs)

Please check whether you can reproduce this or whether there is a problem on my side.

**Comment by ppxasjsm** [comment]
I can reproduce the error and I can identify where things are going 'wrong'. There is also a problem with R2 btw. I'll have a little think about what the right way is to compute these and will push a fix tomorrow.

**Comment by ppxasjsm** [comment]
I understand what the problem is. It's not really an error. Basically, the distributions of R, R2, and tau are not normally distributed and I report confidence intervals based on an ordered list.  The problem is that I report the mean of the distribution plus the confidence intervals of the ordered list. Instead, I should be reporting the median and these confidence intervals or mean and standard deviation. However with the skewed distributions probably the median and confidence intervals are better. 
In fact, I'll change the code in such a way that you have both options. Mean and confidence based on standard error and 95% confidence interval around the median. (This would be the equivalent of a box and whiskers plot). I'll push a fix in a little while.

**Comment by ppxasjsm** [comment]
[This](
https://github.com/michellab/freenrgworkflows/commit/5210dbbd9c9fcb49ced0e51ba5b273f21a5a8640) commit fixes the issue and a new 1.0.1 release was created.
